# Generated by Django 5.1.5 on 2025-02-12 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('bookshelves', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('copyright', models.BooleanField(default=False)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='book.author')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=255)),
                ('occurrences_count', models.IntegerField()),
                ('positions', models.JSONField(blank=True, default=list)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'unique_together': {('word', 'book')},
            },
        ),
    ]
