# Generated by Django 5.1.6 on 2026-02-09 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_index_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=255)),
                ('tf', models.FloatField()),
                ('idf', models.FloatField()),
                ('tfidf', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'unique_together': {('book', 'word')},
            },
        ),
    ]
