# Generated by Django 5.1.6 on 2026-02-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_forwardindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwardindex',
            name='idf',
        ),
        migrations.RemoveField(
            model_name='forwardindex',
            name='tf',
        ),
        migrations.RemoveField(
            model_name='forwardindex',
            name='tfidf',
        ),
        migrations.AddField(
            model_name='forwardindex',
            name='occurrences_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forwardindex',
            name='positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='forwardindex',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
