# Generated by Django 5.1.6 on 2026-02-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_forwardindex_idf_remove_forwardindex_tf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardindex',
            name='idf',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='forwardindex',
            name='tf',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='forwardindex',
            name='tfidf',
            field=models.FloatField(default=0.0),
        ),
    ]
